baseURL = "https://daylightbasementstudio.com/"
languageCode = "en-us"
title = "Daylight Basement Studio"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
publishdir = "docs/"
googleAnalytics = "UA-189102182-1"

[Params]
  #homeTitle = "daylightbasementstudio # Set a different text for the header on the home page
  subtitle = "Game development studio working on our first title: Rightfully, Beary Arms"
  mainSections = ["post","posts"]
  #logo = "smallbrand.png" # Expecting square dimensions
  brand = "brand.png"
  favicon = "hotdoglogo.png"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true

[[Params.bigimg]]
  src = "rba/rbaposter.png"
  desc = "Rightfully, Beary Arms"


[Author]
  name = "dbstudio"
  github = "DaylightBasement"
  itchio = "mmbiscuits"

[[menu.main]]
  identifier = "blog"
  name = "blog"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "games"
  name = "games"
  url = "/games/rightfullybearyarms/"
  weight = 2

[[menu.main]]
  identifier = "rba"
  parent = "games"
  name = "rightfully beary arms"
  url = "/games/rightfullybearyarms/"
  weight = 1

[[menu.main]]
  identifier = "about"
  name = "about"
  url = "/about/"
  weight = 3