baseURL = "http://daylightbasementstudio.com/"
languageCode = "en-us"
title = "Daylight Basement Studio"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[Params]
  #homeTitle = "daylightbasementstudio # Set a different text for the header on the home page
  subtitle = "Game development studio working on our first title: Rightfully, Beary Arms"
  mainSections = ["post","posts"]
  #logo = "smallbrand.png" # Expecting square dimensions
  brand = "brand.png"
  favicon = "hotdoglogo.png"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true

[[Params.bigimg]]
  src = "demovideo.gif"
  desc = "tacos"
#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "tacos"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"


[Author]
  name = "Chris"
  website = "yourwebsite.com"
  email = "youremail@domain.com"
  facebook = "username"
  github = "username"
  reddit = "username"
  itchio = "username"

[[menu.main]]
  identifier = "games"
  name = "games"
  url = "/games/rightfullybearyarms/"
  weight = 1

[[menu.main]]
  identifier = "rba"
  parent = "games"
  name = "rightfully beary arms"
  url = "/games/rightfullybearyarms/"
  weight = 1

[[menu.main]]
  identifier = "blog"
  name = "blog"
  url = "/"
  weight = 2

[[menu.main]]
  identifier = "about"
  name = "about"
  url = "/about/"
  weight = 3